# Gemfile (na raiz do projeto mobile)
source "https://rubygems.org"

gem "fastlane"
gem "fastlane-plugin-flutter_version" # lê versão do pubspec.yaml

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
